// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace VRCZ.Core.CompiledModels
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("0c91e245-c23c-46e8-b43d-b58609739cd8"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var avatarEntityAvatarFavoritesFolder = AvatarEntityAvatarFavoritesFolderEntityType.Create(this);
            var avatarFavoritesFolder = AvatarFavoritesFolderEntityType.Create(this);
            var avatarEntity = AvatarEntityEntityType.Create(this);

            AvatarEntityAvatarFavoritesFolderEntityType.CreateForeignKey1(avatarEntityAvatarFavoritesFolder, avatarFavoritesFolder);
            AvatarEntityAvatarFavoritesFolderEntityType.CreateForeignKey2(avatarEntityAvatarFavoritesFolder, avatarEntity);

            AvatarFavoritesFolderEntityType.CreateSkipNavigation1(avatarFavoritesFolder, avatarEntity, avatarEntityAvatarFavoritesFolder);
            AvatarEntityEntityType.CreateSkipNavigation1(avatarEntity, avatarFavoritesFolder, avatarEntityAvatarFavoritesFolder);

            AvatarEntityAvatarFavoritesFolderEntityType.CreateAnnotations(avatarEntityAvatarFavoritesFolder);
            AvatarFavoritesFolderEntityType.CreateAnnotations(avatarFavoritesFolder);
            AvatarEntityEntityType.CreateAnnotations(avatarEntity);

            AddAnnotation("ProductVersion", "9.0.4");
        }
    }
}
