// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace VRCZ.Core.CompiledModels
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: true, modelId: new Guid("bfcbe5fe-2161-4cc4-971f-055e53cd427d"), entityTypeCount: 0)
        {
        }

        partial void Initialize()
        {
            AddAnnotation("ProductVersion", "9.0.4");
        }
    }
}
