// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using VRCZ.Core.CompiledModels;
using VRCZ.Core.DbContexts;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppDbContext), typeof(AppDbContextModel))]
