name: Code Coverage
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    uses: "./.github/workflows/test.yml"

  generate-coverage-summary:
    name: Generate Code Coverage Summary
    needs: build-and-test
    runs-on: ubuntu-latest

    env:
      coverage-result-artifact-download-path: coverage-results

    steps:
      - name: Download Coverage Result
        id: download-artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ needs.build-and-test.outputs.coverage-result-artifact-name-pattern}}
          path: ${{ env.coverage-result-artifact-download-path }}

      - name: Tree
        run: tree ${{ env.coverage-result-artifact-download-path }}

      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 #v1.3.0
        with:
          filename: ${{ env.coverage-result-artifact-download-path }}/**/**/*.xml
          badge: true
          output: both

      - name: Create Action Summary
        run: cat ${{ github.workspace }}/code-coverage-results.md >> $GITHUB_STEP_SUMMARY
