name: Test

on:
  push:
  pull_request:

jobs:
  build-and-test:

    name: ${{ matrix.project }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        project: ["VRCZ.Core.Tests.Unit"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Upload Coverage Result
      uses: actions/upload-artifact@v4
      with:
        path: coverage/
        
  # generate-code-coverage-summary:
  #   runs-on: ubuntu-latest
  #   needs: build-and-test
    
  #   steps:
  #   - name: Download Coverage Result
  #     id: download-artifacts
  #     uses: actions/download-artifact@v4
  #     with:
  #       path: ${{ env.artifactsPath }}
    
  #   - name: Code Coverage Summary
  #     uses: irongut/CodeCoverageSummary@51cc3a756ddcd398d447c044c02cb6aa83fdae95 #v1.3.0
  #     with:
  #       filename: coverage/**/coverage.cobertura.xml
  #       badge: true
        
