name: Test

on:
  push:
  pull_request:

jobs:
  build-and-test:

    name: build-and-test-${{ matrix.project }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        project: ["test/VRCZ.Core.Tests.Unit"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test ${{ matrix.project }} --no-build --verbosity normal
