name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    name: ${{ matrix.project }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        project: ["VRCZ.Core.Tests.Unit"]

    env:
      coverage-result-artifact-name: coverage-result-${{ matrix.project }}-${{ matrix.os }}
      coverage-result-file-directory: coverage

    outputs:
      coverage-result-file-directory: ${{ env.coverage-result-file-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test test/${{ matrix.project }} --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ${{ env.coverage-result-file-directory }}

      - name: Upload Coverage Result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.coverage-result-artifact-name }}
          path: coverage/

  generate-code-coverage-summary:
    name: Generate Code Coverage Summary
    uses: "./.github/workflows/generate-coverage-summary.yml"
    needs: build-and-test
    with:
      coverage-result-directory: ${{ needs.build-and-test.outputs.coverage-result-file-directory }}
      coverage-result-artifact-name-pattern: "coverage-result-*"
