name: Test

on:
  push:
  pull_request:

jobs:
  build-and-test:

    name: ${{ matrix.project }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        project: ["VRCZ.Core.Tests.Unit"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      uses: zyborg/dotnet-tests-report@ce730c068bb73480dcb37c02d40890bf8b44c953
      with:
        project_path: test/${{ matrix.project }}
        report_name: ${{ matrix.project }}
        report_title: ${{ matrix.project }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
