name: Test

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
    outputs:
      coverage-result-artifact-name-pattern:
        description: "Pattern to match the coverage result artifact name"
        value: "coverage-result-*"

jobs:
  build-and-test:
    name: ${{ matrix.project }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        project: ["VRCZ.Core.Tests.Unit"]

    env:
      coverage-result-artifact-name: coverage-result-${{ matrix.project }}-${{ matrix.os }}
      coverage-result-file-directory: coverage

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test test/${{ matrix.project }} --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ${{ env.coverage-result-file-directory }}

      - name: Upload Coverage Result
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.coverage-result-artifact-name }}
          path: ${{ env.coverage-result-file-directory }}
